instrumentation:
  root: src
  default-excludes: true
  excludes:
    - "**/*.spec.js"
    - "**/*.spec.jsx"
  extensions:
    - .js
    - .jsx
  variable: __coverage__
  es-modules: true
  include-all-sources: true
reporting:
  print: summary
  reports:
    - lcov
  dir: ./coverage
