instrumentation:
  root: src
  default-excludes: true
  excludes:
    - "test/**/*.js"
  extensions:
    - .js
  variable: __coverage__
  es-modules: true
  include-all-sources: true
reporting:
  print: summary
  reports:
    - lcov
  dir: ./test/coverage
